[GOOGLE_APPLICATION_CREDENTIALS_JSON]
type = "service_account"
project_id = "yoyaku-wgs"
private_key_id = "1e8f30336c21542124f7aef81078c371a2d16c16"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFlNXfqP5FUhj0
ZN/b7BhCSK3Wsd3FAVQYWrSt2B1E42SY4oMZMgrhTJk0+iSNCImBxINSpxz64E2r
D3Is+OW6QWAJr2yLotAOIaRks3EB2c9SUa3Xe+lmpj1IN/QZLLO3WT/7QVXuZ9qC
9nYg7k1Rwzb3OrLPlK1KFjHV3r2hiXddsYtqOg8/8o6F4e9jlZTAhA/nnGX6iB5n
+TI298hFHrsSD13klk3TtQrE6Ssn7B5/bgRnyDl+UtuqERBtYvpyGFQ6AU94Qs4H
XZ8lKcbKBu6mx/KvC8G6zU+ElRhHFPrd4JqiFm+Mpvw1kOfSJtIFd+dJ5UbSkvLx
C7gQ1adxAgMBAAECggEAErGjAqNgPixAkMcjKuBN/sy0A0Ut/3lxntzmxyNk6TSX
aevdI+QEcMYq9KaDAfetYqsxI5p+bD+CrwtA07lbUOcAPSq/GoWE701W977C9Fra
cC89EFhnb/WYwugNsY43clO7p/pbP7tp8YTzQCWJTYVvxkaBKpqoa6NSgxciW54x
Ah4exurKMtDhYoGgwD2cnKH0I9Z1q008Sa+I2p5Fi09jhWiDND/vyQzVeMqUr6xR
fe4u+UdrPNdPKUMBVPgNFrfuoI/JL/6lih4pDu6N9hU6AkCf5R//FZqtv8ye+xV2
UwftI1uhpaGGtTRL4a5Nqytwc0q414Ui9Kv8C8BrVwKBgQC7nv1fAD6LCLExfWcU
AJp782+Ust7bBkTa3WFt0tq8XAs9Uw7mxBRZRHy6fJ031/T6iPFuZ7Md0Xea8izc
o1tmW4YnRM4iwnP7/D0vWlN+zvqCEGgurWblp2J8Fah+GGJ5o+CXxa3T9lizmvJD
Iqr0/dXFEjCZCFFlZNqf4n1wywKBgQC2Q/RqzCm8hsaneqRT7kEeoMRZxckDwJz8
emwnFem19yVcJSIG7NZq790mjLV5d4uWu3mBGEkfaILhsCQbAOixDcq7EyN3hZ8a
XxiWnbopicYt/nv0BePEy0GIi2YOUiJE6/MVO8OsHjUKjEXEb8hAFAmWlB6TS1aZ
g3TxnP2tMwKBgAKNu20bl75Us/S0fD6tc2zUd2RSuu3IPA+ui7Du+cMujYicJMvH
R2+fmwL+xzUHX3I5gu+5wZpaS4J0YV/vaUMPY9gM+7FFbEa1vC90z0YekxJKHuDj
w07E5HZD5TMyKcT2Egx+yErmQ3bOWRXI1wLWoZ45DShIELOMl90tO//ZAoGBAKds
NJAFijEK/F/LYDdYm6iutK5h6AvyWkHxknc0wcHMjBzgXylNVIhWXSaUCf7RuP90
pl/XFxQqxE7bpc7IPvakXJ0LL4ES1Ns8jzGLIP4W+Fw3b1TwNBEJQ+FRayWsfJ4i
vt+6TjtEZCSURWHz7FYwEb6nwI48ngfVoQ5vzvXRAoGAQaZL6deuRr6XaTs/XfX9
kZhN1ssFJuFB9uFXL90k1l32tGFeV3daPw0b96yV/9dDuof6rduvyYH9hOZWDCQY
pyKUJHbekmj+NIWDWCLiShZld8NICnF26/GWcux6rFmo4f16LLahlHTvyFWQ6zMz
Nm/da/X34XpcXCrnJXbAWUo=
-----END PRIVATE KEY-----
"""
client_email = "yoyaku-wgs@yoyaku-wgs.iam.gserviceaccount.com"
client_id = "116842966173323569795"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/yoyaku-wgs%40yoyaku-wgs.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[general]
email_user = "sweet.marino@gmail.com"
email_password = "kkks modl nzhy faqd"

